import type { HookEntry } from "../types";

export const sensorHooks: HookEntry[] = [
    {
        name: "useWindowSize",
        slug: "use-window-size",
        category: "Sensors & UI",
        description: "Tracks the current viewport dimensions (width and height) in real-time.",
        sourceFile: "src/hooks/sensors.ts",
        useCases: ["Conditional rendering based on width", "Dynamic canvas sizing", "Responsive layout logic"],
        signature: `function useWindowSize(): { width: number, height: number }`,
        params: [],
        returnType: "{ width: number, height: number }",
        returnDescription: "Object containing current innerWidth and innerHeight",
        examples: [{ title: "Responsive Header", description: "Hide text on small screens", code: `const { width } = useWindowSize(); return width > 600 ? <FullHeader /> : <CompactHeader />;` }]
    },
    {
        name: "useMousePosition",
        slug: "use-mouse-position",
        category: "Sensors & UI",
        description: "Tracks the X and Y coordinates of the mouse relative to the document.",
        sourceFile: "src/hooks/sensors.ts",
        useCases: ["Custom cursor implementation", "Tooltip positioning", "Interactive parallax effects"],
        signature: `function useMousePosition(): { x: number, y: number }`,
        params: [],
        returnType: "{ x: number, y: number }",
        returnDescription: "Current X and Y coordinates",
        examples: [{ title: "Follow Mouse", description: "Position a div at mouse coordinates", code: `const { x, y } = useMousePosition(); return <div style={{ left: x, top: y }} />;` }]
    },
    {
        name: "useOnlineStatus",
        slug: "use-online-status",
        category: "Sensors & UI",
        description: "Returns a boolean indicating whether the user is currently online.",
        sourceFile: "src/hooks/sensors.ts",
        useCases: ["Disable submit buttons when offline", "Show network status indicator", "Retry failed requests"],
        signature: `function useOnlineStatus(): boolean`,
        params: [],
        returnType: "boolean",
        returnDescription: "True if online, false if offline",
        examples: [{ title: "Network Banner", description: "Notify user of offline state", code: `const isOnline = useOnlineStatus(); return !isOnline && <Banner>You are offline</Banner>;` }]
    },
    {
        name: "useHover",
        slug: "use-hover",
        category: "Sensors & UI",
        description: "Detects if a specific element is being hovered using a ref.",
        sourceFile: "src/hooks/sensors.ts",
        useCases: ["Show overlay on hover", "Change animation state", "Trigger tooltips"],
        signature: `function useHover<T>(): [useRef<T>, boolean]`,
        params: [],
        returnType: "[ref, isHovered]",
        returnDescription: "Tuple with a ref object and a boolean status",
        examples: [{ title: "Hover Card", description: "Scale up on hover", code: `const [ref, isHovered] = useHover(); return <div ref={ref} className={isHovered ? 'scale-110' : ''} />;` }]
    },
    {
        name: "useFocus",
        slug: "use-focus",
        category: "Sensors & UI",
        description: "Tracks if a specific element (like an input) currently has focus.",
        sourceFile: "src/hooks/sensors.ts",
        useCases: ["Highlight active inputs", "Show validation hints on focus", "Accessibility enhancements"],
        signature: `function useFocus<T>(): [useRef<T>, boolean]`,
        params: [],
        returnType: "[ref, isFocused]",
        returnDescription: "Tuple with a ref object and a boolean status",
        examples: [{ title: "Styled Input", description: "Change border color on focus", code: `const [ref, isFocused] = useFocus(); return <input ref={ref} style={{ borderColor: isFocused ? 'blue' : 'gray' }} />;` }]
    },
    {
        name: "useIdle",
        slug: "use-idle",
        category: "Sensors & UI",
        description: "Detects user inactivity after a specified duration of no movement or interaction.",
        sourceFile: "src/hooks/sensors.ts",
        useCases: ["Auto-logout user", "Pause videos to save bandwidth", "Hide UI elements when inactive"],
        signature: `function useIdle(ms?: number): boolean`,
        params: [{ name: "ms", type: "number", required: false, default: "3000", description: "Timeout in milliseconds" }],
        returnType: "boolean",
        returnDescription: "True if user is idle",
        examples: [{ title: "Away Message", description: "Show message when idle for 1 min", code: `const isIdle = useIdle(60000); return isIdle && <p>Are you still there?</p>;` }]
    },
    {
        name: "useKeyPress",
        slug: "use-key-press",
        category: "Sensors & UI",
        description: "Returns true if a specific key is currently being pressed.",
        sourceFile: "src/hooks/sensors.ts",
        useCases: ["Game controls", "Shortcuts", "Accessibility navigation"],
        signature: `function useKeyPress(targetKey: string): boolean`,
        params: [{ name: "targetKey", type: "string", required: true, description: "The key name to track" }],
        returnType: "boolean",
        returnDescription: "True if key is pressed",
        examples: [{ title: "Hotkeys", description: "Close modal with Escape", code: `const escPressed = useKeyPress('Escape'); useEffect(() => escPressed && close(), [escPressed]);` }]
    },
    {
        name: "useOrientation",
        slug: "use-orientation",
        category: "Sensors & UI",
        description: "Reactive hook to track device orientation (angle and type).",
        sourceFile: "src/hooks/sensors.ts",
        useCases: ["Landscape-specific views", "Mobile UX enhancements", "Screen rotation logic"],
        signature: `function useOrientation(): { angle: number, type: string }`,
        params: [],
        returnType: "{ angle: number, type: string }",
        returnDescription: "Current orientation object",
        examples: [{ title: "Fullscreen Warning", description: "Ask user to rotate phone", code: `const { type } = useOrientation(); return type.includes('portrait') && <p>Rotate for best experience</p>;` }]
    },
    {
        name: "useNavigatorLanguage",
        slug: "use-navigator-language",
        category: "Sensors & UI",
        description: "Tracks the user's browser language setting.",
        sourceFile: "src/hooks/sensors.ts",
        useCases: ["Automatic i18n detection", "Formatting dates/numbers", "Localized content display"],
        signature: `function useNavigatorLanguage(): string`,
        params: [],
        returnType: "string",
        returnDescription: "Browser language code (e.g., 'en-US')",
        examples: [{ title: "Auto Translation", description: "Log the user language", code: `const lang = useNavigatorLanguage(); console.log('User language:', lang);` }]
    },
    {
        name: "usePageLeave",
        slug: "use-page-leave",
        category: "Sensors & UI",
        description: "Triggers a callback when the user's mouse leaves the document window.",
        sourceFile: "src/hooks/sensors.ts",
        useCases: ["'Wait! Don't leave' discount modals", "Pause game on focus loss", "Analytics tracking"],
        signature: `function usePageLeave(onLeave: () => void): void`,
        params: [{ name: "onLeave", type: "() => void", required: true, description: "Callback function" }],
        returnType: "void",
        returnDescription: "Nothing is returned",
        examples: [{ title: "Exit Intent", description: "Show modal when leaving", code: `usePageLeave(() => setShowExitModal(true));` }]
    }
];
